def call_llm(prompt: str, use_openai: bool, temperature: float = 0.1) -> str:
    from generate import generate_openai_response, call_oobabooga

    context = "You are a specialized assistant that updates a single piece of character state. You respond with only a few words."

    if use_openai:
        return generate_openai_response(context, prompt, max_tokens=50, temperature=temperature)
    else:
        user_settings = {"temperature": temperature, "max_response_length": 50}
        return call_oobabooga(context, prompt, user_settings)

def clean_state_response(character, new_value, current_value):
    """
    Cleans up common unwanted patterns in state responses and handles fallbacks.
    
    Args:
        character: Character object or dict with a name attribute
        new_value: The response from the LLM
        current_value: The previous state value to fall back to if needed
        
    Returns:
        str: Cleaned state value
    """
    if not new_value:
        return current_value
        
    new_value = new_value.strip()
    
    # Clean up common patterns in the response
    char_name_pattern = f"{character.name} is "
    if new_value.startswith(char_name_pattern):
        new_value = new_value[len(char_name_pattern):]
    
    if new_value.startswith("still "):
        new_value = new_value[6:]  # Remove "still " from the beginning
    
    while new_value and new_value[-1] in ".,:;!?-_\"'()[]{}":
        new_value = new_value[:-1]  # Strip punctuation from the end
        
    # If cleaning resulted in an empty string, fallback to the old value
    if not new_value:
        new_value = current_value
        
    return new_value

def update_character_state(
    character,
    state_key: str,
    current_value: str,
    user_message: str,
    bot_message: str,
    use_openai: bool
):
    """
    Prompts the LLM to update one piece of the character's state.

    Args:
        character: An object or dict with at least `.name` and `.personality` attributes.
        state_key (str): The name of the parameter to update (e.g. 'action', 'clothing', 'location', 'mood').
        current_value (str): The current value of that parameter.
        user_message (str): The most recent user message.
        bot_message (str): The character's latest message.
        use_openai (bool): Indicates if we should use openai (as opposed to oobabooga)

    Returns:
        str: The new state value (or the old one if no change).
    """
    prompt = f"""
You are tracking {character.name}'s current {state_key}.
- Previous {state_key}: {current_value}
- {character.name}'s personality: {character.personality}

Recent conversation:
- User: {user_message}
- {character.name}: {bot_message}

Based on this new context, what is the updated {state_key}?
(If there's no change, use the previous {state_key}. Return only a word or two.)
    """.strip()

    raw_response = call_llm(prompt, use_openai)
    
    # Process the response
    new_value = clean_state_response(character, raw_response, current_value)
    
    return new_value

def get_static_state(character, state: str, use_openai: bool, temperature: float = 0.9) -> str:
    """
    Queries the LLM for a specific static state attribute of the character.

    Args:
        character: An object with at least 'name' and 'description' attributes.
        state (str): The state attribute to query (e.g., 'species', 'sex', 'hair_color', 'hairstyle', 'eye_color', 'character_traits').
        use_openai (bool): Whether to use OpenAI's API (True) or Oobabooga (False).
        temperature (float): The temperature setting for creative output (default: 0.9).

    Returns:
        str: The static state value generated by the LLM.
    """
    prompt = (
        f"Character name: {character.name}\n"
        f"Description: {character.description}\n\n"
        f"What is {character.name}'s {state}?\n"
        f"If any information is missing, guess something plausible. Return plain text only, no extra commentary.\n"
        f"{character.name}'s {state} is: "
    )
    response = call_llm(prompt, use_openai, temperature)
    return response.strip()